Updates

diff --git a/bin/a3cosmos-blind-extraction-photometry b/bin/a3cosmos-blind-extraction-photometry
--- a/bin/a3cosmos-blind-extraction-photometry
+++ b/bin/a3cosmos-blind-extraction-photometry
@@ -52,28 +52,51 @@ fi
 
 
 # 
+# Read user input
+# 
+for (( i = 1; i < $#; i++ )); do
+    if [[ "${!i}" == "-out" ]]; then
+        if [[ $i -lt $# ]]; then
+            j=$((i+1))
+            OutputDir="${!j}"
+        fi
+    fi
+done
+
+
+# 
 # Go
 # 
-python "$script_dir"/AlmaCosmos_Photometry_Blind_Extraction_PyBDSM.py $@
-
-if [[ ! -d "Output_Blind_Extraction_Photometry_PyBDSM" ]]; then
-    echo "Error! Failed to find the output directory \"Output_Blind_Extraction_Photometry_PyBDSM\"."
-    exit 255
+if [[ ! -d "$OutputDir" ]] || [[ ! -f "$OutputDir.done" ]]; then
+    date +"%Y-%m-%d %Hh%Mm%Ss %Z" > "$OutputDir.start"
+    python "$script_dir"/AlmaCosmos_Photometry_Blind_Extraction_PyBDSM.py $@
+    date +"%Y-%m-%d %Hh%Mm%Ss %Z" > "$OutputDir.done"
 fi
 
-    
-python "$script_dir"/AlmaCosmos_Photometry_Blind_Extraction_combine_each_image_catalogs.py
-
-if [[ ! -f "Output_Blind_Extraction_Photometry_PyBDSM_Catalog.fits" ]]; then
-    echo "Error! Failed to find the output catalog \"Output_Blind_Extraction_Photometry_PyBDSM_Catalog.fits\"."
+if [[ ! -d "$OutputDir" ]] || [[ ! -f "$OutputDir.done" ]]; then
+    echo "Error! Failed to find the output directory \"$OutputDir\"."
     exit 255
 fi
 
 
-python "$script_dir"/AlmaCosmos_Photometry_Blind_Extraction_get_primary_beam_attenuation.py
+# 
+# combine catalogs
+# 
+python "$script_dir"/AlmaCosmos_Photometry_Blind_Extraction_combine_each_image_catalogs.py "$OutputDir"
 
-if [[ ! -f "Output_Blind_Extraction_Photometry_PyBDSM_Catalog_with_Pbcor.fits" ]]; then
-    echo "Error! Failed to find the output catalog \"Output_Blind_Extraction_Photometry_PyBDSM_Catalog_with_Pbcor.fits\"."
+if [[ ! -f "${OutputDir}_Catalog.fits" ]]; then
+    echo "Error! Failed to find the output catalog \"${OutputDir}_Catalog.fits\"."
+    exit 255
+fi
+
+
+# 
+# get primary beam attenuation
+# 
+python "$script_dir"/AlmaCosmos_Photometry_Blind_Extraction_get_primary_beam_attenuation.py "$OutputDir"
+
+if [[ ! -f "${OutputDir}_Catalog_with_Pbcor.fits" ]]; then
+    echo "Error! Failed to find the output catalog \"${OutputDir}_Catalog_with_Pbcor.fits\"."
     exit 255
 fi
 
